### PR TITLE
Update bootstrap-waitingfor.js

### PR DESCRIPTION
**Pull request by bertoost**
Added "headerText" option.
The "message" still acts like the header by default. 

**headerText boolean false**
If the option is provided as boolean false, it will hide the header and "message" will be set in a paragraph above the progress bar.

**headerText as not empty string**
When provided a headerText not-empty string, "message" becomes content above the progress bar and the headerText string will be set as text inside the H3.

**Added "headerSize" option.**
This will generate a heading corresponding to the size number. Like ```<h1>, <h2>, <h3>``` etc.
Defaults still set to 3.

**Added "headerClass" option.**
Extra class(es) for the header tag.

**Added "contentElement" option.**
Determines the tag of the content element. Defaults set to 'p', which will generate a ```<p>``` tag.

**Added "contentClass" option.**
Extra class(es) for the content tag.

### CODE REVIEW

**Comment by ehpc** [comment]
Bert, thanks for the update. But can you swap spaces for tabs before I will merge it?

**Comment by bertoost** [comment]
No sorry.. This is PSR code standard and my IDE (phpStorm) is configured to work like that. You can do yourself, but spaces are better and even less difficult to understand for VCS like Git.

**Comment by ehpc** [comment]
Well there is an option in phpStorm to convert spaces to tabs but I will do that for you, because I use a tabulator key in this project to control tab stops instead of a space key.

**Comment by bertoost** [comment]
I know.. But since spaces has more pros over tabs I use spaces and not tabs. But you're free to do whatever you want :p

**Comment by ehpc** [comment]
I though the same all my life but after some code meditation I have reached an enlightenment and have been using tabs thereafter :smile:

**Pull request merged**
